import sys,os
SP=os.path.dirname(os.path.abspath(__file__))
p=os.path.join(SP,'..','index.html')
s=open(SP+'/index_v070.html').read()
def R(a,b,cnt=1):
    global s
    n=s.count(a)
    if n!=cnt: sys.exit('count %d for %r'%(n,a[:80]))
    s=s.replace(a,b)
R("const VERSION='0.7.0';","const VERSION='0.8.4';")
R('function cantaro(x,z,sc){const m=lathe(','function cantaro(x,z,sc){if(x||z)addCol(x-0.16,x+0.16,z-0.16,z+0.16);const m=lathe(')
R('function barrel(x,z){const g=new THREE.Group();','function barrel(x,z){addCol(x-0.28,x+0.28,z-0.28,z+0.28);const g=new THREE.Group();')
R('function crate(x,z,r){const b=','function crate(x,z,r){addCol(x-0.34,x+0.34,z-0.34,z+0.34);const b=')
R('function ladder(x,z,s){const g=new THREE.Group();','function ladder(x,z,s){addCol(x-0.12,x+0.12,z-0.3,z+0.3);const g=new THREE.Group();')
R('g.position.set(x,0,z);g.rotation.y=r;scene.add(g)};chair(9.5,-81.6,Math.PI);','g.position.set(x,0,z);g.rotation.y=r;scene.add(g);addCol(x-0.26,x+0.26,z-0.26,z+0.26)};chair(9.5,-81.6,Math.PI);')
R('g.position.set(x,y,z);g.rotation.set(r*0.4,r,r*0.2);scene.add(g)};','g.position.set(x,y,z);g.rotation.set(r*0.4,r,r*0.2);scene.add(g);if(!y)addCol(x-0.28,x+0.28,z-0.28,z+0.28)};')
R('mesh(new THREE.PlaneGeometry(2.4,1.6),lam(0xffffff,{map:rugTex}),9.5,0.035,-82.5)','mesh(new THREE.PlaneGeometry(2.4,1.6),lam(0xffffff,{map:rugTex}),9.5,0.06,-82.5)')
R('if(S.past&&!S.flags.done){const hk=(S.t*0.11)%2;const u=hk<1?hk:2-hk;horse.position.set(-1.6,0,-134+u*78);',"if(S.past&&!S.flags.done){const hk=(S.t*0.11)%2;const u=hk<1?hk:2-hk;const hz=-134+u*78,hdir=hk<1?1:-1,ahead=(P.z-hz)*hdir;let off=0;if(ahead>-1.5&&ahead<10&&Math.abs(P.x+1.6)<2.6)off=(P.x<-1.6?1:-1)*(2.6-Math.abs(P.x+1.6));S.hoff=(S.hoff||0)+(off-(S.hoff||0))*Math.min(1,dt*5);const hx=Math.max(-3.6,Math.min(3.6,-1.6+S.hoff));horse.position.set(hx,0,hz);if(S.mode==='play'&&Math.abs(P.z-hz)<2.2&&Math.abs(P.x-hx)<2.2){P.x+=(P.x<hx?-1:1)*dt*3;collide();if(S.t-(S.horseT||-99)>8){S.horseT=S.t;tell([['Juan Preciado',T('horseAside')]])}}")
R("S.mode='play';hint(T('hintMove'),8);","S.mode='play';hint(T('hintMoveRoad'),8);")
R("if(id==='eduviges'){f.reb=1;","if(id==='eduviges'){S.touchedWater=true;S.check={x:0,z:-57};f.reb=1;")
R("e2'),()=>{VOICES[1].active=true;VOICES[2].active=true;S.flags.gallop=true}","e2'),()=>{VOICES[1].active=true;S.flags.gallop=true}")
R("{id:'caballo',x:13.6,z:-80,","{id:'caballo',x:7.4,z:-87.2,")
R("if(q.to){S.check={x:10,z:-84};","if(q.to){S.check={x:10,z:-84};S.breath=1;")
R("if(!S.frags.caballo)return VOICES[2];","if(!S.frags.eduviges)return VOICES[1];if(!S.frags.caballo)return VOICES[2];")
R("if(!f.edu)return{x:6,z:-84};","if(!S.touchedWater)return{x:pozo.x,z:pozo.z+2};if(!f.edu)return{x:6,z:-84};")
R("for(const sd of[-1,1]){box(0.3,0.14,43,stoneMat,sd*4.3,0.07,-76.5)}","for(const sd of[-1,1]){box(0.85,0.12,43,stoneMat,sd*4.475,0.06,-76.5)}")
R("box(0.55,0.14,1.7,stoneMat,fx+s*0.27,0.07,z)","box(0.55,0.14,1.7,stoneMat,fx+s*0.27,Math.abs(fx)<5?0.19:0.07,z)")
R("cantaro(-3.9,-60);cantaro(-3.7,-60.5,0.8);cantaro(-3.95,-61.1,1.1);barrel(3.9,-58.5);crate(3.8,-59.4,0.3);crate(3.85,-59.4,0.1)","cantaro(-3.75,-60);cantaro(-3.6,-60.5,0.8);cantaro(-3.75,-61.1,1.1);barrel(3.7,-58.5);crate(3.6,-59.4,0.3);crate(3.6,-59.4,0.1)")
R("barrel(-3.8,-95.5);barrel(-3.5,-96.2);cantaro(3.8,-91.8);cantaro(3.6,-92.4,0.7);crate(3.7,-96.5,0.5);","barrel(-3.7,-95.5);barrel(-3.45,-96.2);cantaro(3.7,-91.8);cantaro(3.55,-92.4,0.7);crate(3.5,-96.5,0.5);")
R("if(Math.abs(pz-dz)<1)continue;","if(Math.abs(pz-dz)<1.4||Math.abs(pz-wz)<1.3||(d>9&&Math.abs(pz-(cz+(dz>cz?1:-1)*d*0.36))<1.3))continue;")
R("const sh=box(1.8,0.06,0.06,darkWood,1.9,0.35,sz,g);sh.rotation.z=0.4","const sh=box(1.8,0.06,0.06,darkWood,1.93,0.42,sz,g);sh.rotation.z=-0.4")
R("['',S.ecos.length===4?T('ecoLast'):T('ecoRule')]]","['',S.ecos.length===4?T('ecoLast'):T('ecoRule')],['',T('moreBreath')]]")
R(".mlist{margin-top:10px;max-width:420px;width:100%}",".mlist{margin-top:10px;max-width:420px;width:100%;max-height:38vh;overflow:auto}\n.card.x{text-decoration:line-through;opacity:.45}")
R('<div id="end" class="ov">','<div id="choice" class="ov"><div class="panel"><h2 id="choiceQ"></h2><div id="choiceOpts"></div></div></div>\n<div id="end" class="ov">')
R("function groundH(x,z){let h=0;","function groundH(x,z){if(x>150)return zoneH(x,z);let h=0;")
R("const hm=L(0xffffff,strawTex,true);cyl(0.27,0.27,","const hm=L(0xffffff,o.hatTex||strawTex,true);cyl(o.brim||0.27,o.brim||0.27,")
R("const juan=human(JUAN);","const juan=human(JUAN);let PL=juan;")
i18n=open(SP+'/ch_i18n.js').read()
R("let LANG=((navigator.language","%slet LANG=((navigator.language"%i18n)
R("hist:[],histT:0,t:0,seq:null,touchedWater:false};","hist:[],histT:0,t:0,seq:null,touchedWater:false,zone:'comala',exv:{},found:{},zf:{}};")
R("addEventListener('keydown',e=>{if(e.code==='Tab')","addEventListener('keydown',e=>{if(e.code==='KeyE'&&!e.repeat&&S.mode==='play')S.ePress=true;if(e.code==='Tab')")
R("A.next={bell:20,door:9,pluck:4,gal:0,bark:6,violin:5};loadClips()}","A.next={bell:20,door:9,pluck:4,gal:0,bark:6,violin:5};zoneAudio();loadClips()}")
R("const buf=A.clips[t.eco?(t.frag?'fr_'+t.frag:'echoMurmur'):'fr_'+t.id];","const buf=A.clips[t.eco?(t.frag?'fr_'+t.frag:'echoMurmur'):'fr_'+(t.clip||t.id)];")
R("['amb','music','voices','sfx','pastAmb'].forEach(k=>{A[k].gain.cancel","['amb','music','voices','sfx','pastAmb','zone'].forEach(k=>{if(!A[k])return;A[k].gain.cancel")
R("VOICES.forEach(v=>{const on=v.active&&v.past===S.past&&!v.done;let target=on?1.0:(v.done&&v.past===S.past?0.12:0);","VOICES.forEach(v=>{const h=here(v);const on=v.active&&h&&!v.done;let target=on?1.0:(v.done&&h&&!v.zone?0.12:0);")
R("if(!S.past&&S.mode==='play'){if(n.bell<0)","if(!S.past&&S.mode==='play'&&S.zone==='comala'){if(n.bell<0)")
R("if(S.past&&S.mode==='play'){if(n.bark<0)","if(S.past&&S.mode==='play'&&(S.zone==='comala'||S.zone==='plaza')){if(n.bark<0)")
R("VOICES.forEach(v=>{if(!v.active||v.done||v.past!==S.past)return;","VOICES.forEach(v=>{if(!v.active||v.done||!here(v))return;")
R("if(ORDER.includes(id)&&ORDER.every(k=>S.frags[k]))S.after.push(openPuzzle);if(S.mode!=='card')runAfter()}","if(ORDER.includes(id)&&ORDER.every(k=>S.frags[k]))S.after.push(openPuzzle);zoneFrag(id);if(S.mode!=='card')runAfter()}")
R("function objective(){const f=S.flags;","function objective(){if(S.zone!=='comala')return zoneObjective();const f=S.flags;")
R("function finishListen(t){if(t.eco)","function finishListen(t){if(t.quiet){$('listen').textContent='';completeFrag(t.id);return}if(t.eco)")
R("function setWorld(past){S.past=past;","function setWorld(past){S.past=past;S.pal=null;")
R("()=>setTimeout(()=>endGame(T('endCard')(Object.keys(S.frags).length,S.ecos.length)),1500)","()=>seq([[1.2,()=>fadeTo(startCh3)]])")
R("$('bookList').innerHTML=['rebozo','eduviges','caballo','p1','p2','p3','p4'].map(id=>'<div class=\"frag\">'+(S.frags[id]?'<em>'+FR[id].title+'</em>'+FR[id].text:'<i>'+T('blank')+'</i>')+'</div>').join('');",
  "$('bookList').innerHTML=BOOK.map(id=>'<div class=\"frag\">'+(S.frags[id]?'<em>'+FR[id].title+'</em>'+FR[id].text:'<i>'+T('blank')+'</i>')+'</div>').join('')+(EXIDS.some(k=>S.exv[k])?'<h2 style=\"margin-top:1em\">'+T('exvotos')+'</h2>'+EXIDS.concat(S.exv.fin?['fin']:[]).filter(k=>k==='fin'||S.exv[k]).map(k=>'<div class=\"frag\"><em>'+T('ex')[k][0]+'</em>'+T('ex')[k][1]+'</div>').join(''):'');")
R("if(['title','end','book','puzzle','menu','card'].includes(S.mode))return;","if(['title','end','book','puzzle','menu','card','choice'].includes(S.mode))return;")
R("function jumpTo(id){cam.yaw=0;","function jumpTo(id){resetZone();S.fade=null;$('choice').classList.remove('on');$('end').classList.remove('on');cam.yaw=0;")
R("if(id==='final'){pastSetup();","if(id==='velorio')startCh3();\nif(id==='renteria'){['w1','w2','pedro'].forEach(k=>S.frags[k]=true);startRenteria()}\nif(id==='retablo'){['w1','w2','pedro','maria','ana','renteria'].forEach(k=>S.frags[k]=true);startRetablo()}\nif(id==='excusado')startCh4();\nif(id==='papalote'){S.frags.pensar=true;startHill();place(SUS.x,SUS.z+5,Math.PI)}\nif(id==='puerta'){S.frags.pensar=S.frags.papalote=true;doorSetup()}\nif(id==='fulgor')startCh5();\nif(id==='cerca'){mediaSetup();startFence();place(Z5-1.5,7,Math.PI)}\nif(id==='viudas')startViudas();\nif(id==='final'){pastSetup();")
R("P.y=groundH(P.x,P.z);juan.g.position.set(P.x,P.y,P.z);cam.pos.set(P.x+Math.sin(cam.yaw)*5,P.y+3.5,P.z+Math.cos(cam.yaw)*5)}","P.y=groundH(P.x,P.z);PL.g.position.set(P.x,P.y,P.z);cam.pos.set(P.x+Math.sin(cam.yaw)*5,P.y+3.5,P.z+Math.cos(cam.yaw)*5)}")
R("eduviges.head.rotation.y=Math.sin(S.t*0.5)*0.3}","eduviges.head.rotation.y=Math.sin(S.t*0.5)*0.3;zoneNPC(dt)}")
a=s.index('function update(dt){');b=s.index('setWorld(false);\njuan.g.position.set')
s=s[:a]+open(SP+'/ch_update.js').read()+open(SP+'/ch_main.js').read()+'\n'+s[b:]
open(p,'w').write(s)
print('ok',len(s))
