CA = {
'lang': 'ca', 'locale': 'ca_ES', 'path': '/ca/', 'play': '/jugar',
'title': 'Pedro Páramo, el videojoc · Survival horror gratuït basat en la novel·la de Juan Rulfo',
'desc': 'Juga gratis al navegador a Pedro Páramo, un survival horror de PS1 a l\'estil de Silent Hill basat en la novel·la de Juan Rulfo, amb veus en català. A més: resum, personatges, Comala, temes i biografia de Rulfo.',
'ogalt': 'Juan Preciado davant d\'una casa de Comala enmig de la boira',
'skip': 'Salta al contingut',
'nav': [('juego', 'El joc'), ('murmullos', 'Murmuris'), ('novela', 'La novel·la'), ('personajes', 'Personatges'), ('rulfo', 'Juan Rulfo'), ('preguntas', 'Preguntes')],
'navlabel': 'Seccions',
'langlabel': 'Idioma',
'playbtn': 'Juga',
'sound_on': 'Activa el murmuri de fons',
'sound_off': 'Silencia el murmuri de fons',
'eyebrow': 'Survival horror · basat en la novel·la de Juan Rulfo',
'quote': 'Vaig venir a Comala perquè em van dir que aquí vivia el meu pare, un tal Pedro Páramo.',
'quote_cite': 'Juan Rulfo, <cite>Pedro Páramo</cite> (1955)',
'hero_cta': 'Baixa a Comala',
'hero_cta2': 'Escolta els morts',
'chips': ['Gratuït', 'Al navegador', '12 capítols', 'Català · Español · English', 'Amb auriculars'],
'mobile_note': 'Pedro Páramo es juga amb teclat i ratolí. Desa\'t l\'enllaç i obre\'l a l\'ordinador.',
'share': 'Copia l\'enllaç',
'shared': 'Enllaç copiat',
'game_h': 'Un survival horror al poble dels morts',
'game_p': [
    'En Juan Preciado baixa a Comala a buscar el seu pare. La calor li pren l\'alè, el poble és buit i les veus dels morts surten de les parets. <strong>Pedro Páramo</strong> és un videojoc gratuït de navegador que explica la novel·la de Juan Rulfo com un survival horror de la primera PlayStation: polígons mínims, boira, vèrtexs que tremolen i murmuris en 3D.',
    'No hi ha monstres per matar. La por és en allò que se sent, en allò que es recorda i en el poc que dura l\'aire. Cadascun dels dotze capítols es juga d\'una manera diferent, seguint l\'ordre en què la novel·la va deixant anar els fragments.',
],
'features': [
    ('La calor', 'Comala és damunt de les brases de la terra. Caminar sota el sol gasta l\'alè; el pou i l\'ombra te\'l tornen.'),
    ('Les veus', 'Mantén E per escoltar els morts. Cada veu és un fragment del llibre que es guarda al teu quadern.'),
    ('Els ecos', 'Si caus, deixes un eco que repeteix les teves passes. Els ecos allarguen l\'alè, però el poble es va omplint de tu.'),
],
'chapters_h': 'Els dotze capítols',
'chapters': [
    ('El camí', 'En Juan baixa a Comala amb l\'Abundio, el traginer.', 'Caminar sota el sol sense quedar-se sense alè.'),
    ('La casa de l\'Eduviges', 'L\'Eduviges li explica la nit en què va morir en Miguel Páramo.', 'Escoltar les veus de la casa i ordenar els records.'),
    ('Miguel Páramo', 'La vetlla, el pare Rentería i les monedes.', 'Sigil a la vetlla i les monedes del retaule.'),
    ('La infància d\'en Pedro', 'En Pedro de nen, la Susana i els estels.', 'Pensar per viatjar i fer volar un estel al ritme del vent.'),
    ('La Media Luna', 'En Pedro es fa amo de tot.', 'Una elecció que no és elecció i una tanca que et segueix.'),
    ('Damiana', 'La Damiana Cisneros porta en Juan pel poble de nit.', 'Seguir la llum del seu fanal: fora d\'ella l\'aire s\'acaba.'),
    ('En Donis i la seva germana', 'Els germans, el fang i els murmuris de la plaça.', 'Fugir del fang i caminar entre els murmuris.'),
    ('La tomba', 'En Juan, enterrat al costat de la Dorotea, sent la Susana San Juan.', 'Girar el cap i estirar les veus.'),
    ('Susana San Juan', 'La mina, el mar i les campanes.', 'Baixar la Susana amb la corda i fer callar una festa.'),
    ('La Revolució', 'Els revoltats arriben a la Media Luna.', 'Amagar-se dels genets darrere les pedres.'),
    ('Comala es mor de gana', 'En Pedro es creua de braços.', 'No fer res mentre el poble es buida.'),
    ('El final', 'L\'Abundio i en Pedro Páramo.', 'Recordar assegut, una última elecció i unes últimes passes.'),
],
'chapter_word': 'Capítol',
'how_label': 'Com es juga',
'murm_h': 'Escolta els murmuris',
'murm_p': 'A Comala els morts no callen. Toca una veu per sentir-la: són les mateixes que trobaràs al joc.',
'murm_play': 'Escolta',
'murm_stop': 'Para',
'novel_h': 'Pedro Páramo, la novel·la',
'novel_lead': '<cite>Pedro Páramo</cite> és l\'única novel·la que l\'escriptor mexicà Juan Rulfo va publicar en vida. Va sortir el març de 1955 al Fondo de Cultura Económica i avui es considera una de les obres cabdals de la literatura en castellà del segle XX.',
'summary_h': 'Resum sense espòilers',
'summary': [
    'En Juan Preciado promet a la seva mare, la Dolores, que anirà a Comala a fer pagar al seu pare el que els deu. El pare es diu Pedro Páramo. Pel camí l\'acompanya l\'Abundio, un traginer que li diu que ell també és fill d\'en Pedro Páramo i que en Pedro Páramo va morir fa molts anys.',
    'Comala és un poble buit, ardent, ple d\'ecos. En Juan s\'allotja a casa de l\'Eduviges Dyada, que l\'esperava perquè la seva mare l\'havia avisada. A poc a poc descobreix que les persones amb qui parla ja no són vives i que tot el poble murmura.',
    'Entre la veu d\'en Juan s\'escola una altra història: la d\'en Pedro Páramo, el nen enamorat de la Susana San Juan que es va convertir en el cacic de la Media Luna, amo de les terres, de les dones i de la gent de Comala.',
],
'spoiler_h': 'Resum complet (amb espòilers)',
'spoiler': [
    'A en Juan Preciado el maten els murmuris. Es desperta enterrat a la mateixa tomba que la Dorotea, una captaire, i des d\'allà tots dos escolten els morts del cementiri, entre ells la Susana San Juan.',
    'La història d\'en Pedro Páramo es reconstrueix a trossos. Després de l\'assassinat del seu pare, en Pedro es casa amb la Dolores Preciado per no haver-li de pagar els deutes, fa córrer les tanques sobre les terres dels veïns i fa penjar en Toribio Aldrete amb l\'ajuda del seu administrador, en Fulgor Sedano. El seu fill Miguel Páramo viola i mata quan vol, fins que mor en caure del cavall. El pare Rentería, el germà del qual va morir a mans d\'en Miguel, accepta les monedes d\'en Pedro i l\'absol.',
    'En Pedro aconsegueix que la Susana San Juan torni a Comala amb el seu pare, en Bartolomé, a qui fa matar. La Susana ha perdut el seny i viu en el record d\'en Florencio, el seu marit mort, i del mar. Quan mor, el poble celebra una fira amb les campanes que toquen a morts per ella. En Pedro jura creuar-se de braços i deixa que Comala es mori de gana. Durant la Revolució pacta amb els revoltats per continuar manant.',
    'Al final, l\'Abundio, borratxo i desesperat per la mort de la seva dona, va a demanar-li ajuda i l\'apunyala. En Pedro Páramo, assegut a la seva cadira, s\'esfondra com un munt de pedres.',
],
'structure_h': 'Una novel·la feta de murmuris',
'structure': [
    'La novel·la no té capítols: són uns setanta fragments que salten entre el present d\'en Juan Preciado i el passat d\'en Pedro Páramo, entre veus de vius i de morts, sense avisar. Rulfo la va arribar a titular <em>Los murmullos</em> (Els murmuris). Llegir-la és muntar un trencaclosques, i el joc et demana el mateix: recollir fragments i ordenar el que va passar.',
    'Per això la novel·la es llegeix com una precursora del realisme màgic: els morts parlen amb naturalitat, el temps no avança en línia recta i el paisatge té el pes d\'un personatge.',
],
'themes_h': 'Temes i claus de lectura',
'themes': [
    ('La mort', 'Tots els habitants de Comala són morts i continuen parlant. La mort no és un final, és un lloc.'),
    ('El pare absent', 'En Juan busca un pare que mai no el va reconèixer. En Pedro Páramo té fills per tot el poble i no és pare de cap.'),
    ('El cacic', 'En Pedro Páramo concentra la terra, la llei i l\'església. La novel·la retrata el caciquisme del camp mexicà.'),
    ('La culpa i la religió', 'El pare Rentería ven el perdó. Les ànimes en pena no troben qui resi per elles.'),
    ('La memòria', 'Els personatges viuen en els seus records: la Susana en el mar, en Pedro en la Susana, la Dolores en una Comala verda que ja no existeix.'),
    ('La Revolució i la Cristiada', 'Les guerres passen per la Media Luna i en Pedro les fa servir per continuar manant.'),
],
'chars_h': 'Personatges de Pedro Páramo',
'chars': [
    ('Juan Preciado', 'Fill d\'en Pedro Páramo i la Dolores Preciado. Arriba a Comala per complir la promesa feta a la seva mare. És el protagonista del joc.'),
    ('Pedro Páramo', 'Cacic de la Media Luna. Amo de tot Comala, enamorat tota la vida de la Susana San Juan.'),
    ('Susana San Juan', 'L\'amor d\'infància d\'en Pedro. Torna a Comala ja perduda en els records d\'en Florencio i del mar.'),
    ('Dolores Preciado', 'Mare d\'en Juan. En Pedro s\'hi va casar per les seves terres i ella va acabar marxant de Comala.'),
    ('Abundio Martínez', 'Traginer i fill d\'en Pedro Páramo. Guia en Juan fins a Comala i tanca la història.'),
    ('Eduviges Dyada', 'Amiga de la Dolores. Acull en Juan a casa seva, tot i que ja és morta: es va treure la vida.'),
    ('Miguel Páramo', 'L\'únic fill que en Pedro va reconèixer. Violent i abusador, mor en caure del cavall.'),
    ('El pare Rentería', 'Capellà de Comala. La seva consciència es trenca en absoldre en Miguel a canvi de monedes.'),
    ('Fulgor Sedano', 'Administrador de la Media Luna. Executa els negocis i les amenaces d\'en Pedro.'),
    ('Damiana Cisneros', 'Criada de la Media Luna que va cuidar en Juan de petit. Se li apareix de nit.'),
    ('Dorotea', 'Captaire que buscava noies per a en Miguel. Comparteix tomba amb en Juan.'),
    ('En Donis i la seva germana', 'Dos germans que viuen com a marit i muller en una casa sense sostre.'),
    ('Toribio Aldrete', 'Veí que s\'enfronta a en Pedro per les tanques i acaba penjat.'),
    ('Bartolomé San Juan', 'Pare de la Susana. En Pedro el fa matar per quedar-se-la.'),
],
'comala_h': 'On és Comala?',
'comala': [
    'La Comala de Rulfo és un poble inventat. Existeix una Comala real a l\'estat de Colima, però la de la novel·la s\'assembla més als pobles del sud de Jalisco on va créixer Rulfo, com San Gabriel. Rulfo va explicar que el nom ve de <em>comal</em>, la planxa de fang que es posa sobre les brases: Comala és un lloc que crema.',
    'L\'Abundio ho diu a la novel·la: allà fa tanta calor que els qui es moren i van a l\'infern tornen a buscar la flassada. Al joc aquesta calor és l\'amenaça principal: l\'alè se t\'acaba sota el sol.',
],
'rulfo_h': 'Juan Rulfo',
'rulfo': [
    'Juan Rulfo va néixer el 16 de maig de 1917 a Jalisco, Mèxic, i va créixer a San Gabriel. El seu pare va ser assassinat quan ell tenia sis anys i la seva mare va morir poc després; va passar part de la infància en un orfenat de Guadalajara. Aquesta terra de violència, de la Revolució i de la guerra cristera, és el paisatge de tota la seva obra.',
    'Amb només dos llibres va canviar la literatura en castellà: <cite>El llano en llamas</cite> (1953), contes, i <cite>Pedro Páramo</cite> (1955). Gabriel García Márquez va explicar que es va arribar a saber la novel·la de memòria, i Jorge Luis Borges la va considerar una de les millors novel·les de les literatures en llengua hispànica. Rulfo també va ser un gran fotògraf. Va morir a Ciutat de Mèxic el 7 de gener de 1986.',
],
'timeline': [('1917', 'Neix a Jalisco'), ('1953', '<cite>El llano en llamas</cite>'), ('1955', '<cite>Pedro Páramo</cite>'), ('1983', 'Premi Príncep d\'Astúries'), ('1986', 'Mor a Ciutat de Mèxic')],
'adapt_h': 'De la novel·la al joc',
'adapt_p': 'Cada mecànica surt d\'una imatge del llibre.',
'adapt': [
    ('«Allà fa tanta calor…»', 'L\'alè que es gasta sota el sol.'),
    ('«Em van matar els murmuris»', 'Escoltar els morts costa aire.'),
    ('Els fragments solts', 'Un quadern on ordenar el que sents.'),
    ('Els estels d\'en Pedro i la Susana', 'Fer volar un estel al ritme del vent.'),
    ('En Pedro es creua de braços', 'Un capítol sencer en què no fer res.'),
    ('La tomba compartida amb la Dorotea', 'Girar el cap sota terra i estirar les veus.'),
],
'faq_h': 'Preguntes freqüents',
'faq': [
    ('És gratuït?', 'Sí. Es juga gratis al navegador, sense anuncis, sense registre i sense descarregar res.'),
    ('En quins dispositius es juga?', 'En un ordinador amb teclat i ratolí (Windows, macOS o Linux) i un navegador actual com Chrome, Firefox, Edge o Safari. Al mòbil pots llegir aquesta pàgina, però el joc necessita teclat.'),
    ('Cal haver llegit la novel·la?', 'No. El joc explica la història des del principi. Si l\'has llegida, reconeixeràs les veus i hi trobaràs picades d\'ullet; si no, pot ser una bona porta d\'entrada.'),
    ('Fa por?', 'És un survival horror d\'atmosfera, a l\'estil dels jocs de terror de PlayStation de finals dels noranta: boira, silenci i veus. Sense ensurts barats ni violència explícita.'),
    ('Es desa la partida?', 'Sí. Es desa sola al navegador en començar cada capítol i pots continuar des de la pantalla de títol.'),
    ('En quins idiomes és?', 'En català, castellà i anglès, amb veus en els tres idiomes.'),
    ('Té relació amb la pel·lícula de Netflix?', 'No. La pel·lícula <cite>Pedro Páramo</cite> (2024) de Rodrigo Prieto i aquest joc són adaptacions independents de la mateixa novel·la.'),
    ('Qui l\'ha fet?', 'El disseny, el codi, l\'art, el so i les veus són obra de Claude, una IA d\'Anthropic. En Santiago hi va fer de pont com a AI engineer. És un projecte de fans sense ànim de lucre i el codi és obert.'),
],
'final_h': 'Comala t\'espera',
'final_p': 'Posa\'t els auriculars. Abaixa el volum del món.',
'credits': 'Projecte de fans sense ànim de lucre. <cite>Pedro Páramo</cite> és obra de Juan Rulfo (1955); els fragments citats pertanyen als seus hereus. Disseny, codi, art, so i veus: Claude (Anthropic). AI engineer: Santiago.',
'repo': 'Codi a GitHub',
'top': 'Torna a dalt',
}
