ES = {
'lang': 'es', 'locale': 'es_ES', 'path': '/', 'play': '/jugar',
'title': 'Pedro Páramo, el videojuego · Survival horror gratis basado en la novela de Juan Rulfo',
'desc': 'Juega gratis en el navegador a Pedro Páramo, un survival horror de PS1 al estilo de Silent Hill basado en la novela de Juan Rulfo. Además: resumen, personajes, Comala, temas y biografía de Rulfo.',
'ogalt': 'Juan Preciado ante una casa de Comala entre la niebla',
'skip': 'Saltar al contenido',
'nav': [('juego', 'El juego'), ('murmullos', 'Murmullos'), ('novela', 'La novela'), ('personajes', 'Personajes'), ('rulfo', 'Juan Rulfo'), ('preguntas', 'Preguntas')],
'navlabel': 'Secciones',
'langlabel': 'Idioma',
'playbtn': 'Jugar',
'sound_on': 'Activar el murmullo de fondo',
'sound_off': 'Silenciar el murmullo de fondo',
'eyebrow': 'Survival horror · basado en la novela de Juan Rulfo',
'quote': 'Vine a Comala porque me dijeron que acá vivía mi padre, un tal Pedro Páramo.',
'quote_cite': 'Juan Rulfo, <cite>Pedro Páramo</cite> (1955)',
'hero_cta': 'Bajar a Comala',
'hero_cta2': 'Escuchar a los muertos',
'chips': ['Gratis', 'En el navegador', '12 capítulos', 'Español · Català · English', 'Con auriculares'],
'mobile_note': 'Pedro Páramo se juega con teclado y ratón. Guárdate el enlace y ábrelo en el ordenador.',
'share': 'Copiar el enlace',
'shared': 'Enlace copiado',
'game_h': 'Un survival horror en el pueblo de los muertos',
'game_p': [
    'Juan Preciado baja a Comala a buscar a su padre. El calor le quita el aliento, el pueblo está vacío y las voces de los muertos salen de las paredes. <strong>Pedro Páramo</strong> es un videojuego gratuito de navegador que cuenta la novela de Juan Rulfo como un survival horror de la primera PlayStation: polígonos mínimos, niebla, vértices que tiemblan y murmullos en 3D.',
    'No hay monstruos que matar. El miedo está en lo que se oye, en lo que se recuerda y en lo poco que dura el aire. Cada uno de los doce capítulos se juega de una forma distinta, siguiendo el orden en que la novela va soltando sus fragmentos.',
],
'features': [
    ('El calor', 'Comala está sobre las brasas de la tierra. Caminar bajo el sol gasta el aliento; el pozo y la sombra te lo devuelven.'),
    ('Las voces', 'Mantén E para escuchar a los muertos. Cada voz es un fragmento del libro que se guarda en tu cuaderno.'),
    ('Los ecos', 'Si caes, dejas un eco que repite tus pasos. Los ecos alargan tu aliento, pero el pueblo se va llenando de ti.'),
],
'chapters_h': 'Los doce capítulos',
'chapters': [
    ('El camino', 'Juan baja a Comala con Abundio, el arriero.', 'Caminar bajo el sol sin quedarse sin aliento.'),
    ('La casa de Eduviges', 'Eduviges le cuenta la noche en que murió Miguel Páramo.', 'Escuchar las voces de la casa y ordenar los recuerdos.'),
    ('Miguel Páramo', 'El velorio, el padre Rentería y las monedas.', 'Sigilo en el velorio y las monedas del retablo.'),
    ('La infancia de Pedro', 'Pedro niño, Susana y los papalotes.', 'Pensar para viajar y volar un papalote al ritmo del viento.'),
    ('La Media Luna', 'Pedro se hace dueño de todo.', 'Una elección que no es elección y una cerca que te sigue.'),
    ('Damiana', 'Damiana Cisneros lleva a Juan por el pueblo de noche.', 'Seguir la luz de su farol: fuera de ella el aire se acaba.'),
    ('Donis y su hermana', 'Los hermanos, el lodo y los murmullos de la plaza.', 'Huir del lodo y caminar entre los murmullos.'),
    ('La tumba', 'Juan, enterrado junto a Dorotea, oye a Susana San Juan.', 'Girar la cabeza y tirar de las voces.'),
    ('Susana San Juan', 'La mina, el mar y las campanas.', 'Bajar a Susana por la cuerda y callar una fiesta.'),
    ('La Revolución', 'Los alzados llegan a la Media Luna.', 'Esconderse de los jinetes detrás de las piedras.'),
    ('Comala se muere de hambre', 'Pedro se cruza de brazos.', 'No hacer nada mientras el pueblo se vacía.'),
    ('El final', 'Abundio y Pedro Páramo.', 'Recordar sentado, una última elección y unos últimos pasos.'),
],
'chapter_word': 'Capítulo',
'how_label': 'Cómo se juega',
'murm_h': 'Escucha los murmullos',
'murm_p': 'En Comala los muertos no se callan. Toca una voz para oírla: son las mismas que encontrarás en el juego.',
'murm_play': 'Escuchar',
'murm_stop': 'Parar',
'novel_h': 'Pedro Páramo, la novela',
'novel_lead': '<cite>Pedro Páramo</cite> es la única novela publicada en vida por el escritor mexicano Juan Rulfo. Salió en marzo de 1955 en el Fondo de Cultura Económica y hoy se considera una de las obras cumbre de la literatura en español del siglo XX.',
'summary_h': 'Resumen sin spoilers',
'summary': [
    'Juan Preciado le promete a su madre, Dolores, que irá a Comala a cobrarle a su padre lo que les debe. El padre se llama Pedro Páramo. En el camino lo acompaña Abundio, un arriero que le dice que él también es hijo de Pedro Páramo y que Pedro Páramo murió hace muchos años.',
    'Comala es un pueblo vacío, caliente, lleno de ecos. Juan se aloja en casa de Eduviges Dyada, que lo esperaba porque su madre le avisó. Poco a poco descubre que las personas con las que habla ya no están vivas y que el pueblo entero murmura.',
    'Entre la voz de Juan se cuela otra historia: la de Pedro Páramo, el niño enamorado de Susana San Juan que se convirtió en el cacique de la Media Luna, dueño de las tierras, de las mujeres y de la gente de Comala.',
],
'spoiler_h': 'Resumen completo (con spoilers)',
'spoiler': [
    'A Juan Preciado lo matan los murmullos. Despierta enterrado en la misma tumba que Dorotea, una mendiga, y desde ahí los dos escuchan a los muertos del cementerio, entre ellos a Susana San Juan.',
    'La historia de Pedro Páramo se reconstruye a pedazos. Tras el asesinato de su padre, Pedro se casa con Dolores Preciado para no pagarle sus deudas, manda correr las cercas sobre las tierras de sus vecinos y hace colgar a Toribio Aldrete con la ayuda de su administrador, Fulgor Sedano. Su hijo Miguel Páramo viola y mata a su antojo, hasta que muere al caer de su caballo. El padre Rentería, cuyo hermano murió a manos de Miguel, acepta las monedas de Pedro y lo absuelve.',
    'Pedro consigue que Susana San Juan vuelva a Comala con su padre, Bartolomé, al que manda matar. Susana ha perdido la razón y vive en el recuerdo de Florencio, su marido muerto, y del mar. Cuando muere, el pueblo celebra una feria con las campanas que doblan por ella. Pedro jura cruzarse de brazos y deja que Comala se muera de hambre. Durante la Revolución pacta con los alzados para seguir mandando.',
    'Al final, Abundio, borracho y desesperado por la muerte de su mujer, va a pedirle ayuda y lo apuñala. Pedro Páramo, sentado en su equipal, se desmorona como un montón de piedras.',
],
'structure_h': 'Una novela hecha de murmullos',
'structure': [
    'La novela no tiene capítulos: son unos setenta fragmentos que saltan entre el presente de Juan Preciado y el pasado de Pedro Páramo, entre voces de vivos y de muertos, sin avisar. Rulfo llegó a titularla <em>Los murmullos</em>. Leerla es armar un rompecabezas, y el juego te pide lo mismo: recoger fragmentos y ordenar lo que pasó.',
    'Por eso la novela se lee como precursora del realismo mágico: los muertos hablan con naturalidad, el tiempo no avanza en línea recta y el paisaje tiene el peso de un personaje.',
],
'themes_h': 'Temas y claves de lectura',
'themes': [
    ('La muerte', 'Todos los habitantes de Comala están muertos y siguen hablando. La muerte no es un final, es un lugar.'),
    ('El padre ausente', 'Juan busca a un padre que nunca lo reconoció. Pedro Páramo tiene hijos por todo el pueblo y no es padre de ninguno.'),
    ('El cacique', 'Pedro Páramo concentra la tierra, la ley y la iglesia. La novela retrata el caciquismo del campo mexicano.'),
    ('La culpa y la religión', 'El padre Rentería vende el perdón. Las almas en pena no encuentran quien rece por ellas.'),
    ('La memoria', 'Los personajes viven en sus recuerdos: Susana en el mar, Pedro en Susana, Dolores en una Comala verde que ya no existe.'),
    ('La Revolución y la Cristiada', 'Las guerras pasan por la Media Luna y Pedro las usa para seguir mandando.'),
],
'chars_h': 'Personajes de Pedro Páramo',
'chars': [
    ('Juan Preciado', 'Hijo de Pedro Páramo y Dolores Preciado. Llega a Comala a cumplir la promesa hecha a su madre. Es el protagonista del juego.'),
    ('Pedro Páramo', 'Cacique de la Media Luna. Dueño de todo Comala, enamorado toda su vida de Susana San Juan.'),
    ('Susana San Juan', 'El amor de infancia de Pedro. Vuelve a Comala ya perdida en sus recuerdos de Florencio y del mar.'),
    ('Dolores Preciado', 'Madre de Juan. Pedro se casó con ella por sus tierras y ella acabó yéndose de Comala.'),
    ('Abundio Martínez', 'Arriero e hijo de Pedro Páramo. Guía a Juan hasta Comala y cierra la historia.'),
    ('Eduviges Dyada', 'Amiga de Dolores. Recibe a Juan en su casa, aunque ya está muerta: se quitó la vida.'),
    ('Miguel Páramo', 'El único hijo que Pedro reconoció. Violento y abusador, muere al caer de su caballo.'),
    ('El padre Rentería', 'Cura de Comala. Su conciencia se rompe al absolver a Miguel a cambio de monedas.'),
    ('Fulgor Sedano', 'Administrador de la Media Luna. Ejecuta los negocios y las amenazas de Pedro.'),
    ('Damiana Cisneros', 'Criada de la Media Luna que cuidó a Juan de niño. Se le aparece de noche.'),
    ('Dorotea', 'Mendiga que buscaba muchachas para Miguel. Comparte tumba con Juan.'),
    ('Donis y su hermana', 'Dos hermanos que viven como marido y mujer en una casa sin techo.'),
    ('Toribio Aldrete', 'Vecino que se enfrenta a Pedro por sus cercas y acaba colgado.'),
    ('Bartolomé San Juan', 'Padre de Susana. Pedro lo manda matar para quedarse con ella.'),
],
'comala_h': '¿Dónde está Comala?',
'comala': [
    'La Comala de Rulfo es un pueblo inventado. Existe un Comala real en el estado de Colima, pero el de la novela se parece más a los pueblos del sur de Jalisco donde creció Rulfo, como San Gabriel. Rulfo explicó que el nombre viene de <em>comal</em>, la plancha de barro que se pone sobre las brasas: Comala es un lugar que arde.',
    'Abundio lo dice en la novela: allá hace tanto calor que los que se mueren y van al infierno regresan por su cobija. En el juego ese calor es la amenaza principal: el aliento se te acaba bajo el sol.',
],
'rulfo_h': 'Juan Rulfo',
'rulfo': [
    'Juan Rulfo nació el 16 de mayo de 1917 en Jalisco, México, y creció en San Gabriel. Su padre fue asesinado cuando él tenía seis años y su madre murió poco después; pasó parte de su infancia en un orfanato de Guadalajara. Esa tierra de violencia, de la Revolución y la guerra cristera, es el paisaje de toda su obra.',
    'Con apenas dos libros cambió la literatura en español: <cite>El llano en llamas</cite> (1953), cuentos, y <cite>Pedro Páramo</cite> (1955). Gabriel García Márquez contó que llegó a saberse la novela de memoria, y Jorge Luis Borges la llamó una de las mejores novelas de las literaturas de lengua hispánica. Rulfo fue también un gran fotógrafo. Murió en la Ciudad de México el 7 de enero de 1986.',
],
'timeline': [('1917', 'Nace en Jalisco'), ('1953', '<cite>El llano en llamas</cite>'), ('1955', '<cite>Pedro Páramo</cite>'), ('1983', 'Premio Príncipe de Asturias'), ('1986', 'Muere en Ciudad de México')],
'adapt_h': 'De la novela al juego',
'adapt_p': 'Cada mecánica sale de una imagen del libro.',
'adapt': [
    ('«Allá hace tanto calor…»', 'El aliento que se gasta bajo el sol.'),
    ('«Me mataron los murmullos»', 'Escuchar a los muertos cuesta aire.'),
    ('Los fragmentos sueltos', 'Un cuaderno donde ordenar lo que oyes.'),
    ('Los papalotes de Pedro y Susana', 'Volar un papalote al ritmo del viento.'),
    ('Pedro se cruza de brazos', 'Un capítulo entero en el que no hacer nada.'),
    ('La tumba compartida con Dorotea', 'Girar la cabeza bajo tierra y tirar de las voces.'),
],
'faq_h': 'Preguntas frecuentes',
'faq': [
    ('¿Es gratis?', 'Sí. Se juega gratis en el navegador, sin anuncios, sin registro y sin descargar nada.'),
    ('¿En qué dispositivos se juega?', 'En un ordenador con teclado y ratón (Windows, macOS o Linux) y un navegador actual como Chrome, Firefox, Edge o Safari. En el móvil puedes leer esta página, pero el juego necesita teclado.'),
    ('¿Hace falta haber leído la novela?', 'No. El juego cuenta la historia desde el principio. Si la has leído, reconocerás las voces y encontrarás guiños; si no, puede ser una buena puerta de entrada.'),
    ('¿Da miedo?', 'Es un survival horror de atmósfera, al estilo de los juegos de terror de PlayStation de finales de los noventa: niebla, silencio y voces. No hay sustos baratos ni violencia explícita.'),
    ('¿Se guarda la partida?', 'Sí. Se guarda sola en tu navegador al empezar cada capítulo y puedes continuar desde la pantalla de título.'),
    ('¿En qué idiomas está?', 'En español, catalán e inglés, con voces en los tres idiomas.'),
    ('¿Tiene relación con la película de Netflix?', 'No. La película <cite>Pedro Páramo</cite> (2024) de Rodrigo Prieto y este juego son adaptaciones independientes de la misma novela.'),
    ('¿Quién lo ha hecho?', 'El diseño, el código, el arte, el sonido y las voces son obra de Claude, una IA de Anthropic. Santiago hizo de puente como AI engineer. Es un proyecto de fans sin ánimo de lucro y su código es abierto.'),
],
'final_h': 'Comala te está esperando',
'final_p': 'Ponte los auriculares. Baja el volumen del mundo.',
'credits': 'Proyecto de fans sin ánimo de lucro. <cite>Pedro Páramo</cite> es obra de Juan Rulfo (1955); los fragmentos citados pertenecen a sus herederos. Diseño, código, arte, sonido y voces: Claude (Anthropic). AI engineer: Santiago.',
'repo': 'Código en GitHub',
'top': 'Volver arriba',
}
