EN = {
'lang': 'en', 'locale': 'en_US', 'path': '/en/', 'play': '/jugar',
'title': 'Pedro Páramo, the video game · Free survival horror based on Juan Rulfo\'s novel',
'desc': 'Play Pedro Páramo free in your browser: a PS1 survival horror in the style of Silent Hill based on Juan Rulfo\'s novel. Plus: summary, characters, Comala, themes and a short biography of Rulfo.',
'ogalt': 'Juan Preciado in front of a house in Comala, in the fog',
'skip': 'Skip to content',
'nav': [('juego', 'The game'), ('murmullos', 'Whispers'), ('novela', 'The novel'), ('personajes', 'Characters'), ('rulfo', 'Juan Rulfo'), ('preguntas', 'FAQ')],
'navlabel': 'Sections',
'langlabel': 'Language',
'playbtn': 'Play',
'sound_on': 'Turn on the background murmur',
'sound_off': 'Mute the background murmur',
'eyebrow': 'Survival horror · based on the novel by Juan Rulfo',
'quote': 'I came to Comala because I was told my father lived here, a man named Pedro Páramo.',
'quote_cite': 'Juan Rulfo, <cite>Pedro Páramo</cite> (1955)',
'hero_cta': 'Go down to Comala',
'hero_cta2': 'Listen to the dead',
'chips': ['Free', 'In your browser', '12 chapters', 'English · Español · Català', 'Best with headphones'],
'mobile_note': 'Pedro Páramo is played with keyboard and mouse. Save the link and open it on your computer.',
'share': 'Copy the link',
'shared': 'Link copied',
'game_h': 'A survival horror in the town of the dead',
'game_p': [
    'Juan Preciado goes down to Comala to find his father. The heat steals his breath, the town is empty and the voices of the dead seep out of the walls. <strong>Pedro Páramo</strong> is a free browser game that tells Juan Rulfo\'s novel as a first-PlayStation survival horror: minimal polygons, fog, wobbling vertices and whispers in 3D.',
    'There are no monsters to kill. The fear lives in what you hear, in what is remembered and in how little air you have left. Each of the twelve chapters plays differently, following the order in which the novel lets its fragments go.',
],
'features': [
    ('The heat', 'Comala sits on the embers of the earth. Walking in the sun spends your breath; the well and the shade give it back.'),
    ('The voices', 'Hold E to listen to the dead. Each voice is a fragment of the book that is kept in your notebook.'),
    ('The echoes', 'If you fall, you leave an echo that repeats your steps. Echoes make your breath last longer, but the town fills up with you.'),
],
'chapters_h': 'The twelve chapters',
'chapters': [
    ('The road', 'Juan goes down to Comala with Abundio, the mule driver.', 'Walk under the sun without running out of breath.'),
    ('Eduviges\'s house', 'Eduviges tells him about the night Miguel Páramo died.', 'Listen to the voices of the house and put the memories in order.'),
    ('Miguel Páramo', 'The wake, Father Rentería and the coins.', 'Stealth at the wake and the coins on the altarpiece.'),
    ('Pedro\'s childhood', 'Young Pedro, Susana and the kites.', 'Think to travel and fly a kite with the wind.'),
    ('The Media Luna', 'Pedro becomes the owner of everything.', 'A choice that is no choice and a fence that follows you.'),
    ('Damiana', 'Damiana Cisneros leads Juan through the town at night.', 'Follow the light of her lantern: outside it, the air runs out.'),
    ('Donis and his sister', 'The siblings, the mud and the murmurs of the square.', 'Escape the mud and walk among the murmurs.'),
    ('The grave', 'Buried next to Dorotea, Juan hears Susana San Juan.', 'Turn your head and pull at the voices.'),
    ('Susana San Juan', 'The mine, the sea and the bells.', 'Lower Susana on the rope and silence a fiesta.'),
    ('The Revolution', 'The rebels reach the Media Luna.', 'Hide from the riders behind the rocks.'),
    ('Comala starves', 'Pedro folds his arms.', 'Do nothing while the town empties.'),
    ('The end', 'Abundio and Pedro Páramo.', 'Remember from a chair, one last choice and a few last steps.'),
],
'chapter_word': 'Chapter',
'how_label': 'How it plays',
'murm_h': 'Listen to the whispers',
'murm_p': 'In Comala the dead never stop talking. Tap a voice to hear it: they are the same ones you will find in the game.',
'murm_play': 'Listen',
'murm_stop': 'Stop',
'novel_h': 'Pedro Páramo, the novel',
'novel_lead': '<cite>Pedro Páramo</cite> is the only novel the Mexican writer Juan Rulfo published in his lifetime. It came out in March 1955 from Fondo de Cultura Económica and is now considered one of the summits of twentieth-century literature in Spanish.',
'summary_h': 'Summary without spoilers',
'summary': [
    'Juan Preciado promises his dying mother, Dolores, that he will go to Comala and make his father pay what he owes them. His father\'s name is Pedro Páramo. On the way he is joined by Abundio, a mule driver who tells him he is also a son of Pedro Páramo, and that Pedro Páramo died many years ago.',
    'Comala is an empty, scorching town full of echoes. Juan stays at the house of Eduviges Dyada, who was expecting him because his mother told her he would come. Little by little he discovers that the people he talks to are no longer alive and that the whole town is murmuring.',
    'Woven through Juan\'s voice is another story: that of Pedro Páramo, the boy in love with Susana San Juan who became the cacique of the Media Luna, owner of the land, the women and the people of Comala.',
],
'spoiler_h': 'Full summary (spoilers)',
'spoiler': [
    'The murmurs kill Juan Preciado. He wakes up buried in the same grave as Dorotea, a beggar woman, and from there the two of them listen to the dead in the cemetery, among them Susana San Juan.',
    'Pedro Páramo\'s story is pieced together in fragments. After his father is murdered, Pedro marries Dolores Preciado so he won\'t have to pay his debts to her, moves his fences onto his neighbours\' land and has Toribio Aldrete hanged with the help of his steward, Fulgor Sedano. His son Miguel Páramo rapes and kills as he pleases until he dies falling from his horse. Father Rentería, whose brother was killed by Miguel, accepts Pedro\'s coins and absolves him.',
    'Pedro brings Susana San Juan back to Comala with her father, Bartolomé, whom he has killed. Susana has lost her mind and lives in the memory of Florencio, her dead husband, and of the sea. When she dies, the town holds a fair while the bells toll for her. Pedro swears to fold his arms and lets Comala starve. During the Revolution he makes deals with the rebels to stay in power.',
    'In the end Abundio, drunk and desperate after his wife\'s death, comes to ask him for help and stabs him. Pedro Páramo, sitting in his chair, crumbles like a heap of stones.',
],
'structure_h': 'A novel made of whispers',
'structure': [
    'The novel has no chapters: it is about seventy fragments that jump between Juan Preciado\'s present and Pedro Páramo\'s past, between the voices of the living and the dead, without warning. Rulfo once meant to call it <em>Los murmullos</em> (The Murmurs). Reading it is like putting a puzzle together, and the game asks the same of you: gather the fragments and work out what happened.',
    'That is why the novel is read as a forerunner of magical realism: the dead speak as if it were nothing, time does not move in a straight line and the landscape weighs as much as any character.',
],
'themes_h': 'Themes and keys to reading',
'themes': [
    ('Death', 'Everyone in Comala is dead and still talking. Death is not an ending, it is a place.'),
    ('The absent father', 'Juan looks for a father who never acknowledged him. Pedro Páramo has children all over town and is a father to none.'),
    ('The cacique', 'Pedro Páramo holds the land, the law and the church. The novel portrays the rural bossism of Mexico.'),
    ('Guilt and religion', 'Father Rentería sells forgiveness. The souls in torment find nobody to pray for them.'),
    ('Memory', 'The characters live inside their memories: Susana in the sea, Pedro in Susana, Dolores in a green Comala that no longer exists.'),
    ('Revolution and the Cristero War', 'The wars sweep through the Media Luna and Pedro uses them to stay in charge.'),
],
'chars_h': 'Characters in Pedro Páramo',
'chars': [
    ('Juan Preciado', 'Son of Pedro Páramo and Dolores Preciado. He comes to Comala to keep the promise he made to his mother. The main character of the game.'),
    ('Pedro Páramo', 'Cacique of the Media Luna. Owner of all Comala, in love with Susana San Juan his whole life.'),
    ('Susana San Juan', 'Pedro\'s childhood love. She returns to Comala already lost in her memories of Florencio and the sea.'),
    ('Dolores Preciado', 'Juan\'s mother. Pedro married her for her land, and in the end she left Comala.'),
    ('Abundio Martínez', 'Mule driver and son of Pedro Páramo. He guides Juan to Comala and closes the story.'),
    ('Eduviges Dyada', 'Dolores\'s friend. She takes Juan into her house, even though she is already dead: she took her own life.'),
    ('Miguel Páramo', 'The only son Pedro acknowledged. Violent and abusive, he dies falling from his horse.'),
    ('Father Rentería', 'Comala\'s priest. His conscience breaks when he absolves Miguel in exchange for coins.'),
    ('Fulgor Sedano', 'Steward of the Media Luna. He carries out Pedro\'s deals and threats.'),
    ('Damiana Cisneros', 'A servant at the Media Luna who looked after Juan as a baby. She appears to him at night.'),
    ('Dorotea', 'A beggar who found girls for Miguel. She shares a grave with Juan.'),
    ('Donis and his sister', 'Two siblings living as husband and wife in a house without a roof.'),
    ('Toribio Aldrete', 'A neighbour who stands up to Pedro over his fences and ends up hanged.'),
    ('Bartolomé San Juan', 'Susana\'s father. Pedro has him killed to keep her.'),
],
'comala_h': 'Where is Comala?',
'comala': [
    'Rulfo\'s Comala is an invented town. There is a real Comala in the state of Colima, but the one in the novel is closer to the towns of southern Jalisco where Rulfo grew up, such as San Gabriel. Rulfo explained that the name comes from <em>comal</em>, the clay griddle placed over hot coals: Comala is a place that burns.',
    'Abundio says it in the novel: it is so hot there that those who die and go to hell come back for their blankets. In the game that heat is the main threat: your breath runs out under the sun.',
],
'rulfo_h': 'Juan Rulfo',
'rulfo': [
    'Juan Rulfo was born on 16 May 1917 in Jalisco, Mexico, and grew up in San Gabriel. His father was murdered when he was six and his mother died soon after; he spent part of his childhood in an orphanage in Guadalajara. That land of violence, of the Revolution and the Cristero War, is the landscape of all his work.',
    'With just two books he changed literature in Spanish: <cite>The Burning Plain</cite> (<cite>El llano en llamas</cite>, 1953), a collection of stories, and <cite>Pedro Páramo</cite> (1955). Gabriel García Márquez said he came to know the novel by heart, and Jorge Luis Borges called it one of the finest novels in Spanish-language literature. Rulfo was also a remarkable photographer. He died in Mexico City on 7 January 1986.',
],
'timeline': [('1917', 'Born in Jalisco'), ('1953', '<cite>The Burning Plain</cite>'), ('1955', '<cite>Pedro Páramo</cite>'), ('1983', 'Prince of Asturias Award'), ('1986', 'Dies in Mexico City')],
'adapt_h': 'From the novel to the game',
'adapt_p': 'Every mechanic comes from an image in the book.',
'adapt': [
    ('“It\'s so hot there…”', 'Breath that runs out under the sun.'),
    ('“The murmurs killed me”', 'Listening to the dead costs air.'),
    ('The loose fragments', 'A notebook in which to order what you hear.'),
    ('Pedro and Susana\'s kites', 'Flying a kite with the wind.'),
    ('Pedro folds his arms', 'A whole chapter in which you do nothing.'),
    ('The grave shared with Dorotea', 'Turning your head underground and pulling at the voices.'),
],
'faq_h': 'Frequently asked questions',
'faq': [
    ('Is it free?', 'Yes. It is played free in the browser, with no ads, no sign-up and nothing to download.'),
    ('What devices does it run on?', 'On a computer with keyboard and mouse (Windows, macOS or Linux) and a current browser such as Chrome, Firefox, Edge or Safari. You can read this page on your phone, but the game needs a keyboard.'),
    ('Do I need to have read the novel?', 'No. The game tells the story from the beginning. If you have read it you will recognise the voices and find nods to the book; if not, it can be a good way in.'),
    ('Is it scary?', 'It is an atmospheric survival horror in the style of late-nineties PlayStation horror games: fog, silence and voices. No cheap jump scares and no explicit violence.'),
    ('Does it save my progress?', 'Yes. It saves automatically in your browser at the start of each chapter, and you can continue from the title screen.'),
    ('What languages is it in?', 'English, Spanish and Catalan, with voices in all three languages.'),
    ('Is it related to the Netflix film?', 'No. The film <cite>Pedro Páramo</cite> (2024) by Rodrigo Prieto and this game are independent adaptations of the same novel.'),
    ('Who made it?', 'The design, code, art, sound and voices are the work of Claude, an AI by Anthropic. Santiago acted as the bridge, as AI engineer. It is a non-profit fan project and its code is open source.'),
],
'final_h': 'Comala is waiting for you',
'final_p': 'Put on your headphones. Turn the world down.',
'credits': 'Non-profit fan project. <cite>Pedro Páramo</cite> is the work of Juan Rulfo (1955); the quoted fragments belong to his heirs. Design, code, art, sound and voices: Claude (Anthropic). AI engineer: Santiago.',
'repo': 'Code on GitHub',
'top': 'Back to top',
}
