const {chromium}=require('playwright');const path=require('path'),fs=require('fs'),http=require('http');
const root='/mnt/project-files/pedro-paramo-poc';
const server=http.createServer((q,r)=>{const f=path.join(root,decodeURIComponent(q.url.split('?')[0]));if(!fs.existsSync(f)||fs.statSync(f).isDirectory()){r.writeHead(404);return r.end()}fs.createReadStream(f).pipe(r)});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));
const b=await chromium.launch({args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const pg=await b.newPage({viewport:{width:640,height:480}});
const errs=[];pg.on('pageerror',e=>errs.push(e.message+' '+e.stack));
await pg.route('**/three.min.js',r=>r.fulfill({path:process.env.THREE_LOCAL,contentType:'application/javascript'}));
await pg.goto(`http://127.0.0.1:${server.address().port}/jugar.html#m-velorio`);await pg.waitForTimeout(500);await pg.click('#start');await pg.waitForTimeout(500);
await pg.evaluate(()=>{window.adv=s=>{for(let i=0;i<s*20;i++){if(S.mode==='card'){S.cardT=1;S.cardReady=true;closeCard()}update(0.05)}};window.st=()=>({zone:S.zone,ch:S.ch,mode:S.mode,lock:S.lock,sub:document.getElementById('sub').innerText})});
const step=async(name,fn)=>{const r=await pg.evaluate(fn);console.log(name.padEnd(14),JSON.stringify(r));if(errs.length){console.log('ERR',errs.join('\n'));errs.length=0}};
await step('velorio',()=>{adv(1);['w1','w2','pedro'].forEach(k=>completeFrag(k));adv(40);return st()});
await step('renteria',()=>{completeFrag('maria');completeFrag('ana');completeFrag('renteria');adv(16);return st()});
await step('retablo',()=>{searchNiche('virgen');searchNiche('miguel');searchNiche('pedro');searchNiche('ana');adv(22);return st()});
await step('excusado',()=>{adv(6);completeFrag('pensar');adv(5);return st()});
await step('hill',()=>{P.x=SUS.x;P.z=SUS.z+2.5;adv(14);return st()});
await step('kite',()=>{S.kite.a=0.99;keys.KeyE=true;S.kite.ph='gust';S.kite.t=0;adv(1);keys.KeyE=false;adv(1);return st()});
await step('follow',()=>{S.kite.u=0.999;P.x=Z4-4;P.z=-2;adv(2);return st()});
await step('door',()=>{P.x=Z4-4;P.z=1.8;S.ePress=true;adv(0.1);completeFrag('madre');adv(14);return st()});
await step('fulgor',()=>{adv(1);P.x=Z5;P.z=-3.4;S.ePress=true;adv(0.1);adv(14);return st()});
await step('choice',()=>{document.getElementById('choiceOpts').children[0].click();adv(6);const a=st();document.getElementById('choiceOpts').children[2].click();adv(20);return [a,st()]});
await step('fence',()=>{P.x=FSTART.x;P.z=FSTART.z;adv(0.2);const pts=[[Z5+3,14],[Z5+14,20],[Z5+14,30],[Z5+6,36],[Z5+1,30],[Z5+0.6,10.2]];for(const[x,z]of pts){const sx=P.x,sz=P.z,n=40;for(let i=1;i<=n;i++){P.x=sx+(x-sx)*i/n;P.z=sz+(z-sz)*i/n;update(0.05)}}adv(2);return [st(),S.fence.len|0]});
await step('toribio',()=>{completeFrag('toribio');adv(35);return st()});
await step('viudas',()=>{['v1','v2','v3','v4','v5'].forEach(k=>completeFrag(k));adv(6);return [st(),VOICES.find(v=>v.id==='madre2').active]});
await step('never',()=>{neverFail();adv(20);return [st(),document.getElementById('endText').innerText]});
await step('book',()=>{S.mode='play';S.exv={e1:1,e5:1};toggleBook();return document.getElementById('bookList').innerText.slice(0,200)});
await pg.screenshot({path:'flow.png'});await b.close();server.close()})();
